openapi: "3.0.2"
info:
  version: 0.1-preview
  title: User Management
  description: Retrieve various informations and personal data about employees in User Mgmt application in Softeam Opus
  license:
    name: MIT
    url: https://github.com/SofteamOuest-Opus/user-mgmt/blob/master/LICENSE
servers:
  - url: http://user-mgmt.k8-dev.wildwidewest.xyz/api/private
    description: Development server  

paths:
  /employees:
    get:
      summary: List all employees
      operationId: listEmployees
      responses:
        '200':
          description: Success
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employees"

  /employee/{id}:
    get:
      summary: Info for a specific employee
      operationId: showEmployeeById
      parameters:
        - name: id
          in: path
          required: true
          description: The id of employee to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employee"
        '404':
          description: No employee with such id
    put:
      summary: Create or update an employee with given id 
      operationId: updateEmployee
      parameters:
        - name: id
          in: path
          required: true
          description: The id of employee to create or update
          schema:
            type: string
        - name: query
          in: body
          required: true
          description: Employee info
          schema:
            $ref: "#/components/schemas/Employee"
      responses:
        '200':
          description: Update successful
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employee"
        '201':
          description: Create successful
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employee"
        '400':
          description: Invalid id or employee info

  /employee:
    post:
      summary: Create a new employee
      operationId: createEmployee
      parameters:
        - name: query
          in: body
          required: true
          description: Employee info
          schema:
            $ref: "#/components/schemas/Employee"
      responses:
        '201':
          description: Creation successful
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employee"
        '400':
          description: Invalid employee info

components:
  schemas:
    Employee:
      required:
        - lastName
        - firstName
        - email
      properties:
        id:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        email:
          type: string
        photoUri:
          type: string
        office:
          $ref: "#/components/schemas/Office"
        manager:
          $ref: "#/components/schemas/Manager"
        humanResourceManager:
          $ref: "#/components/schemas/Manager"
        status:
          $ref: "#/components/schemas/Status"
        function:
          $ref: "#/components/schemas/Function"
        accessRights:
          type: array
          items: 
            type: string

    Employees:
      type: array
      items:
        $ref: "#/components/schemas/Employee"

    Manager:
      required:
        - id
      properties:
        id:
          type: string
        lastName:
          type: string
        firstName:
          type: string

    Office:
      required:
        - id
      properties:
        id:
          type: string
        name:
          type: string

    Status:
      required:
        - id
      properties:
        id:
          type: string
        name:
          type: string

    Function:
      required:
        - id
      properties:
        id:
          type: string
        name:
          type: string

    EmployeeSearch:
      properties:
        id:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        email:
          type: string
